name: xgboost-binder
channels:
- conda-forge
dependencies:
- dask=2021.10.0
- distributed=2021.10.0
- coiled=0.0.54
- pandas>=1.3.0
- python=3.9
- python-snappy
- xgboost
- dask-ml
- dask-xgboost
- scikit-learn
- s3fs>=2021.8.0
- matplotlib
- ipywidgets
- dask-labextension
- jupyterlab
- blosc
- lz4