name: snowflake
channels:
  - defaults
  - conda-forge
dependencies:
  - python==3.9.6
  - coiled
  - dask==2021.11.2
  - distributed==2021.11.2
  - snowflake-connector-python
  - dask-snowflake
  - jupyterlab
  - pyarrow
  - fastparquet
  - dask-labextension
  - ipykernel
  - pandas==1.3.5
  - xgboost
  - ipython
  - ipywidgets
  - lz4
